# Basics of Tensorflow

In [ ]:
import tensorflow as tf
#enabled to get instant output. if you don't need, you can use session concept which was dicussed in lecture videos. 

In [ ]:
a = tf.random.uniform(shape=(1000,8,1,64))
b = tf.random.uniform(shape=(1000,8,1,64))
add =tf.concat([a,b],2)
print(add.shape)

(1000, 8, 2, 64)


## 1.1 Addition
<pre> It is similar to numpy addition.</pre>

In [ ]:
a = tf.random.uniform(shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.76544833, 0.5849211 ],
       [0.6496333 , 0.837142  ]], dtype=float32)>

In [ ]:
b = tf.random.uniform(shape=(2,2))
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.21659184, 0.84143305],
       [0.37285578, 0.34695148]], dtype=float32)>

In [ ]:
add = a + b

In [ ]:
add

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.98204017, 1.4263542 ],
       [1.0224891 , 1.1840935 ]], dtype=float32)>

<pre>Broadcasting works similar to numpy.</pre>

In [ ]:
c = 2.0

In [ ]:
add_2 = a + c

In [ ]:
add_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.7654483, 2.5849211],
       [2.6496334, 2.837142 ]], dtype=float32)>

## 1.2 Subtraction
<pre> It is similar to numpy Subtraction.</pre>

In [ ]:
a = tf.random.uniform(shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.28105927, 0.982491  ],
       [0.4543612 , 0.18095028]], dtype=float32)>

In [ ]:
b = tf.random.uniform(shape=(2,2))
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.4447968 , 0.6860428 ],
       [0.37685537, 0.468835  ]], dtype=float32)>

In [ ]:
sub = a - b

In [ ]:
sub

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.16373754,  0.29644823],
       [ 0.07750583, -0.2878847 ]], dtype=float32)>

## 1.3 Multiplication
<pre>
- For two dimensional matrices, you can multiply (m*n) and (n*p) and get (m*p)
- for 3 dim matrices, you can multiply (b * n * p)  and (b * p * m)  and get (b * n * m).
- ( for any dim, you have to maintain last 2 dim as two dim multiplication and first n-2 dim has to be same.)
</pre>

In [ ]:
a = tf.random.uniform(shape=(3,2))
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.42196798, 0.38027525],
       [0.38185   , 0.22015715],
       [0.5268816 , 0.76247597]], dtype=float32)>

In [ ]:
b = tf.random.uniform(shape=(2,4))
b

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.9718013 , 0.3615694 , 0.95991015, 0.14124382],
       [0.8668082 , 0.6472012 , 0.6082754 , 0.37513733]], dtype=float32)>

In [ ]:
tf.matmul(a, b)# (3*2)@(2*4) = (3*4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.7396947 , 0.3986853 , 0.63636345, 0.20225582],
       [0.56191635, 0.28055125, 0.5004579 , 0.13652311],
       [1.1729445 , 0.68397963, 0.9695544 , 0.36045194]], dtype=float32)>

In [ ]:
a = tf.random.uniform(shape=(3,2,4))
a

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[0.9877397 , 0.48359144, 0.21143746, 0.05832505],
        [0.8771219 , 0.5664412 , 0.4249972 , 0.9969027 ]],

       [[0.900666  , 0.80757594, 0.517033  , 0.28724205],
        [0.7659626 , 0.49534667, 0.6094078 , 0.69295204]],

       [[0.6940073 , 0.846938  , 0.21292734, 0.02632797],
        [0.72752416, 0.3675493 , 0.06150746, 0.7544544 ]]], dtype=float32)>

In [ ]:
b = tf.random.uniform(shape=(3,4,3))
b

<tf.Tensor: shape=(3, 4, 3), dtype=float32, numpy=
array([[[0.11292541, 0.1512934 , 0.18766534],
        [0.8486798 , 0.98399425, 0.34927642],
        [0.00986195, 0.7620127 , 0.4357643 ],
        [0.719465  , 0.4123912 , 0.9612788 ]],

       [[0.20048189, 0.85946274, 0.03512299],
        [0.00274813, 0.01884758, 0.6162877 ],
        [0.21552551, 0.4967357 , 0.53184485],
        [0.73915625, 0.75223136, 0.63248396]],

       [[0.17898035, 0.13221335, 0.60118175],
        [0.82875395, 0.47318816, 0.72319293],
        [0.5212456 , 0.01200008, 0.94683623],
        [0.04532623, 0.28599632, 0.92908216]]], dtype=float32)>

In [ ]:
tf.matmul(a, b) #(3*2*4)@(3*4*3) = (3*2*3)

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[0.56600326, 0.81046045, 0.50247514],
        [1.3012044 , 1.4250448 , 1.50595   ]],

       [[0.5065371 , 1.262211  , 0.98599046],
        [0.79846567, 1.4916272 , 1.0945704 ]],

       [[0.9382977 , 0.5026029 , 1.2557923 ],
        [0.50107753, 0.48661765, 1.4623709 ]]], dtype=float32)>

In [ ]:
a = tf.random.uniform(shape=(3,2,2,4))
a

<tf.Tensor: shape=(3, 2, 2, 4), dtype=float32, numpy=
array([[[[0.54392195, 0.44440365, 0.8161578 , 0.81809855],
         [0.48604417, 0.6547922 , 0.09642994, 0.6497735 ]],

        [[0.3501928 , 0.38135064, 0.6284673 , 0.71008825],
         [0.0629884 , 0.9182203 , 0.38800752, 0.3562292 ]]],


       [[[0.9224924 , 0.19615316, 0.9997004 , 0.08698416],
         [0.24685109, 0.56225   , 0.47307873, 0.31770468]],

        [[0.67780447, 0.91869164, 0.16638637, 0.3535664 ],
         [0.31193638, 0.8197057 , 0.7600075 , 0.05366361]]],


       [[[0.5272769 , 0.96931624, 0.08829355, 0.5524454 ],
         [0.20437789, 0.06762755, 0.95654666, 0.95075655]],

        [[0.0179888 , 0.8104023 , 0.11797357, 0.00331819],
         [0.5841867 , 0.44848788, 0.36709404, 0.9991509 ]]]],
      dtype=float32)>

In [ ]:
b = tf.random.uniform(shape=(3,2,4,3))
b

<tf.Tensor: shape=(3, 2, 4, 3), dtype=float32, numpy=
array([[[[0.2834133 , 0.509132  , 0.46001756],
         [0.97463393, 0.5611937 , 0.5920421 ],
         [0.58850133, 0.81208575, 0.38495648],
         [0.19901109, 0.02336013, 0.37129867]],

        [[0.01351154, 0.24393833, 0.29496288],
         [0.62523425, 0.89000344, 0.3109938 ],
         [0.1713661 , 0.98518586, 0.9721639 ],
         [0.9514363 , 0.88035953, 0.48958528]]],


       [[[0.7863579 , 0.42804885, 0.9072486 ],
         [0.07675076, 0.20902002, 0.3846116 ],
         [0.2522825 , 0.10128736, 0.09820902],
         [0.50040567, 0.5750352 , 0.02917349]],

        [[0.12253606, 0.14205027, 0.02638292],
         [0.635326  , 0.08655989, 0.43645883],
         [0.61891055, 0.1903218 , 0.7276802 ],
         [0.29237318, 0.42028153, 0.7488444 ]]],


       [[[0.5331987 , 0.8180437 , 0.327402  ],
         [0.16922152, 0.84226334, 0.44389403],
         [0.87165594, 0.15138781, 0.07683992],
         [0.7354989 , 0.5659597 , 0.72767

In [ ]:
tf.matmul(a,b) # (3*2*2*4)@(3*2*4*3)=(3*2*2*3)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=float32, numpy=
array([[[[1.2304062 , 1.2082257 , 1.1312634 ],
         [0.96199536, 0.7084141 , 0.8896347 ]],

        [[1.0264668 , 1.6691189 , 1.1805135 ],
         [0.9803746 , 1.5284537 , 0.8557516 ]]],


       [[[1.0361984 , 0.5871477 , 1.0130899 ],
         [0.5155971 , 0.45379412, 0.49593234]],

        [[0.87307584, 0.35606855, 0.80469584],
         [1.0450704 , 0.28246412, 0.95922565]]],


       [[[0.928457  , 1.5737834 , 1.0116925 ],
         [1.653478  , 0.90704966, 0.8622798 ]],

        [[0.90787655, 0.22883625, 0.48853627],
         [1.9012737 , 0.8429649 , 1.3065176 ]]]], dtype=float32)>

## 1. 4 Transpose
<pre>    - matrix transpose. </pre>

In [ ]:
a = tf.random.uniform(shape=(3,2))
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.8037541 , 0.04268324],
       [0.6290544 , 0.30998707],
       [0.06460428, 0.25465047]], dtype=float32)>

In [ ]:
a.shape

TensorShape([3, 2])

In [ ]:
tf.transpose(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.8037541 , 0.6290544 , 0.06460428],
       [0.04268324, 0.30998707, 0.25465047]], dtype=float32)>

* We have a "perm" argument for transpose function, in that you can define your own way to change rows and column positions. as shown below

In [ ]:
a = tf.random.uniform(shape=(3,2,5,4))
a.shape

TensorShape([3, 2, 5, 4])

In [ ]:
a_transpose = tf.transpose(a, perm=[0, 2, 1, 3])

In [ ]:
a_transpose.shape

TensorShape([3, 5, 2, 4])

<pre>My transposed matrix dim changed based on pem values( we transposed 1 and 2 axis only). you can check below example in that we chnaged all the axis</pre>

In [ ]:
a = tf.random.uniform(shape=(3,2,5,4))
a.shape

TensorShape([3, 2, 5, 4])

In [ ]:
a_transpose = tf.transpose(a, perm=[3, 2, 1, 0])

In [ ]:
a_transpose.shape

TensorShape([4, 5, 2, 3])

## 1. 4 Element wise operation

### 1.4.1 Multiply Respective elements in two matrices
Ex: 
<pre>
A = [[1 2],
     [3,4]]

B = [[5,6],
     [7,8]]

we want A*B as 
[A[0][0]*B[0][0], A[0][1]*B[0][1]
A[1][0]*B[1][0], A[1][1]*B[1][1]]
</pre>

In [ ]:
a = tf.random.uniform(shape=(3,2))
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.12988472, 0.5670922 ],
       [0.4760952 , 0.22742903],
       [0.41719067, 0.5343312 ]], dtype=float32)>

In [ ]:
b = tf.random.uniform(shape=(3,2))
b

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.14475429, 0.14347386],
       [0.87398994, 0.20727289],
       [0.89850616, 0.64863753]], dtype=float32)>

In [ ]:
a * b

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.01880137, 0.0813629 ],
       [0.4161024 , 0.04713987],
       [0.3748484 , 0.34658727]], dtype=float32)>

In [ ]:
tf.multiply(a, b)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.01880137, 0.0813629 ],
       [0.4161024 , 0.04713987],
       [0.3748484 , 0.34658727]], dtype=float32)>

<pre>You can do a*b or you can use tf.multiply</pre>

## 1.5 Expanding Dimensions

In [ ]:
a = tf.random.uniform(shape=(3,2))
a.shape

TensorShape([3, 2])

In [ ]:
a_add = tf.expand_dims(a, axis=1)#we are adding an additional axis at 1st dim

In [ ]:
a_add.shape

TensorShape([3, 1, 2])

In [ ]:
a = tf.random.uniform(shape=(3,2))
a.shape

TensorShape([3, 2])

In [ ]:
a_add = tf.expand_dims(a, axis=2)#we are adding an additional axis at 2nd dim

In [ ]:
a_add.shape

TensorShape([3, 2, 1])

## 1.6 Squeezing dimensions

<pre>
Note that we can squeeze along with the axis with shape 1

Ex: 
A.shape= [3,4,1] ==> we can squeez it on axis=2 will give [3,4]
A.shape= [3,1,4] ==> we can squeez it on axis=1 will give [3,4]
A.shape= [1,3,4] ==> we can squeez it on axis=0 will give [3,4]
A.shape= [2,3,4] ==> we can't squeez it on any of the axis

</pre>

In [ ]:
a = tf.random.uniform(shape=(3,1,4))
a.shape

TensorShape([3, 1, 4])

In [ ]:
a_squ = tf.squeeze(a, axis=1)

In [ ]:
a_squ

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.1653527 , 0.37342227, 0.39445853, 0.23488903],
       [0.8684    , 0.9512193 , 0.22936511, 0.7588464 ],
       [0.31096876, 0.07381868, 0.5157198 , 0.10617495]], dtype=float32)>

## 1.7 Reshaping of tensors

<a href='https://www.tensorflow.org/api_docs/python/tf/reshape'> check the documentation </a>

In [ ]:
a = tf.random.uniform(shape=(5,3,4))

# tf.reshape(tensor, [reshape dimensions]])
b = tf.reshape(a, [a.shape[0]*a.shape[1],a.shape[2]])

print(a.shape, b.shape)

(5, 3, 4) (15, 4)
