## Lets Implement GPT-2


In [2]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 42.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 92.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 KB 10.4 MB/s eta 0:00:00


In [3]:
from transformers import pipeline, set_seed
generator = pipeline('text-generation', model='gpt2')
set_seed(42)
generator("Hello, I'm a language model,", max_length=30, num_return_sequences=5)


Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/548M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "Hello, I'm a language model, I'm writing a new language for you. But first, I'd like to tell you about the language itself"},
 {'generated_text': "Hello, I'm a language model, and I'm trying to be as expressive as possible. In order to be expressive, it is necessary to know"},
 {'generated_text': "Hello, I'm a language model, so I don't get much of a license anymore, but I'm probably more familiar with other languages on that"},
 {'generated_text': "Hello, I'm a language model, a functional model... It's not me, it's me!\n\nI won't bore you with how"},
 {'generated_text': "Hello, I'm a language model, not an object model.\n\nIn a nutshell, I need to give language model a set of properties that"}]

In [13]:
from transformers import GPT2Tokenizer, TFGPT2Model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = TFGPT2Model.from_pretrained('gpt2')
text = "i want to get word embeddings for this text?"
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)


All model checkpoint layers were used when initializing TFGPT2Model.

All the layers of TFGPT2Model were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2Model for predictions without further training.


In [14]:
output

TFBaseModelOutputWithPastAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
array([[[ 1.41644999e-02, -1.24915324e-01, -3.35429788e-01, ...,
         -1.57379687e-01, -2.57972293e-02, -7.34403729e-05],
        [-2.21318245e-01, -5.42509258e-01, -5.21081746e-01, ...,
         -1.95749193e-01,  4.85071748e-01,  3.35170925e-01],
        [ 1.81591466e-01, -4.89482254e-01,  6.05689108e-01, ...,
         -6.05640234e-03,  1.90870866e-01,  2.89591581e-01],
        ...,
        [ 1.63778916e-01, -3.18680406e-01, -4.46189672e-01, ...,
          4.82895136e-01,  7.42525011e-02,  5.42965412e-01],
        [ 6.00994043e-02,  1.22934356e-01, -9.19800341e-01, ...,
          3.54772508e-01,  6.49774745e-02,  7.32290149e-01],
        [ 2.19093993e-01, -2.76674390e-01,  2.10522786e-01, ...,
         -1.82133168e-01, -1.85782790e-01, -2.44688720e-01]]],
      dtype=float32)>, past_key_values=(<tf.Tensor: shape=(2, 1, 12, 12, 64), dtype=float32, numpy=
array([[[[[-1

In [26]:
import numpy as np
np.array(output[0][0]).shape

(12, 768)

In [27]:
np.array(encoded_input['input_ids'][0])


array([   72,   765,   284,   651,  1573, 11525,    67,   654,   329,
         428,  2420,    30], dtype=int32)

In [28]:
tokenizer.decode(np.array(encoded_input['input_ids'][0]))

'i want to get word embeddings for this text?'